---

language: python
services: docker

env:
  global:
    - ROLE_NAME: zookeeper
    - USER_NAME: bilalcaliskan
  matrix:
    - MOLECULE_DISTRO: centos7
    - MOLECULE_DISTRO: centos8

install:
  - pip install molecule yamllint ansible-lint docker

before_script:
  - cd ../
  - mv $ROLE_NAME-ansible-role $USER_NAME.$ROLE_NAME
  - cd $USER_NAME.$ROLE_NAME

script:
  - molecule test

notifications:
  webhooks:
    urls:
      - https://galaxy.ansible.com/api/v1/notifications/
    on_success: always
    on_failure: never
    on_start: never
    on_cancel: never
    on_error: never
    if: branch = master
  email:
    on_success: never
    on_failure: always

...
