---

- name: Get service facts
  service_facts:

- name: Set fact before installation
  set_fact:
    zookeeper_installed: false
  when: ansible_facts.services["zookeeper.service"] is not defined

- name: Install required packages
  package:
    name: "{{ item }}"
    state: present
    use: auto
  loop: "{{ required_packages }}"

- name: Ensure {{ group }} group exists
  group:
    name: "{{ group }}"
    state: present

- name: Ensure {{ user }} user exists
  user:
    name: "{{ user }}"
    shell: /sbin/nologin
    group: "{{ group }}"

- name: Check if tar file exists
  stat:
    path: "{{ file_path }}"
  register: file_stat_result

- name: Download tar.gz file
  get_url:
    url: "{{ download_url }}"
    dest: "{{ base_dir_path }}/"
    owner: "{{ user }}"
    group: "{{ group }}"
    mode: 0644
  when: not file_stat_result.stat.exists

- name: Check if directory exists
  stat:
    path: "{{ folder_path }}"
  register: directory_stat_result

- name: Extract tar.gz file
  unarchive:
    src: "{{ file_path }}"
    dest: "{{ base_dir_path }}/"
    owner: "{{ user }}"
    group: "{{ group }}"
    remote_src: true
  when: not directory_stat_result.stat.exists

- name: Create a symlink of unarchived directory
  file:
    src: "{{ folder_path }}"
    dest: "{{ link_path }}"
    owner: "{{ user }}"
    group: "{{ group }}"
    state: link

- name: Create data directory
  file:
    path: "{{ data_dir_path }}"
    state: directory
    owner: "{{ user }}"
    group: "{{ group }}"
    mode: 0755

- name: Include setup_storage.yml conditionally
  include_tasks: setup_storage.yml
  when: (enable_persistency | bool)

- name: Transfer template files to the remote location
  template:
    src: "{{ item.src_path }}"
    dest: "{{ item.dest_path }}"
    owner: "{{ item.user }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
  loop:
    - {src_path: zoo.cfg.j2, dest_path: "{{ link_path }}/conf/zoo.cfg", user: "{{ user }}", group: "{{ group }}", mode: 640}
    - {src_path: myid.j2, dest_path: "{{ data_dir_path }}/myid", user: "{{ user }}", group: "{{ group }}", mode: 640}
    - {src_path: zookeeper.service.j2, dest_path: "{{ systemd_service_file_path }}", user: root, group: root, mode: 640}
  notify:
    - start and enable zookeeper service
    - create a symlink of zookeeper log directory

- name: Change ownership of required directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ user }}"
    group: "{{ group }}"
    mode: 0755
  loop:
    - "{{ folder_path }}"
    - "{{ data_dir_path }}"

- name: Set kernel parameters for Zookeeper
  sysctl:
    name: "{{ item.key }}"
    value: "{{ item.value }}"
    state: present
    reload: true
  loop: "{{ os_required_parameters }}"

- name: Stop firewalld if desired by user
  service:
    name: firewalld
    state: stopped
    enabled: false
  when: not (enable_firewalld | bool)

- name: Firewalld related block
  block:
    - name: Ensure firewalld is started and enabled
      service:
        name: firewalld
        state: started
        enabled: true
      changed_when: false

    - name: Allow zookeeper ports
      firewalld:
        port: "{{ item }}"
        permanent: true
        immediate: true
        state: enabled
      loop:
        - 2181/tcp
        - 2888/tcp
        - 3888/tcp
  when: (enable_firewalld | bool)

- name: Set fact after installation
  set_fact:
    zookeeper_installed: true
  when: ansible_facts.services["zookeeper.service"] is defined
