---

- name: Get service facts
  service_facts:

- name: Check if Zookeeper is installed
  set_fact:
    zookeeper_installed: true
  when: ansible_facts.services["zookeeper.service"] is defined

- name: Remove Zookeeper
  block:
    - name: Ensure Zookeeper service stopped and disabled
      service:
        name: zookeeper
        state: stopped
        enabled: false

    - name: Revoke firewalld permissions if firewalld is running
      firewalld:
        port: "{{ item }}"
        immediate: true
        permanent: true
        state: disabled
      loop:
        - 2181/tcp
        - 2888/tcp
        - 3888/tcp
      when: ansible_facts.services["firewalld.service"].state == "running"

    - name: Include destroy_storage.yml conditionally
      include_tasks: destroy_storage.yml
      when: (enable_persistency | bool)

    - name: Remove zookeeper related directories and files
      file:
        path: "{{ item }}"
        state: absent
      loop:
        - "{{ data_dir_path }}"
        - "{{ folder_path }}"
        - "{{ link_path }}"
        - "{{ systemd_service_file_path }}"
      notify: force systemd to reread configs

    - name: Ensure {{ user }} user no more exists
      user:
        name: "{{ user }}"
        state: absent

    - name: Ensure {{ group }} group no more exists
      group:
        name: "{{ group }}"
        state: absent
  rescue:
    - name: Fail and print message
      fail:
        msg: "Got an error inside block, try to rerun tasks with -v option"
  when: ansible_facts.services["zookeeper.service"] is defined
