---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  ignore_errors: true
  tasks:
    - name: Ensure Zookeeper client port is reachable
      wait_for:
        host: localhost
        port: 2181
        timeout: 5

...
