---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  tasks:
    - name: Ensure Zookeeper client port is reachable
      wait_for:
        host: localhost
        port: "{{ item }}"
        timeout: 3
      loop:
        - 2181
        - 2888
        - 3888

...
