---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  tasks:
    - name: Ensure all the Zookeeper related ports are reachable
      wait_for:
        host: localhost
        port: "{{ item }}"
        timeout: 3
      loop:
        - 2188
        - 2888
        - 3888

...
